type Courses = {
  id: number;
  title: string;
  courseCategoryId: number;
  duration: string;
  level: string;
  levelNumber: number;
  averageReviewRating: number;
  numOfReviews: number;
  coverImageId: number;
  recordStatus: string;
  slug: string;
  subTitle: string;
  isFree: boolean;
  basePrice: number;
  discountedPrice: null;
  discountRemainingTime: null;
  discountType: null;
  img: string;
};
